AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'

require:
  - rubocop-capybara

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
