AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'

plugins:
  - rubocop-rails
  - rubocop-minitest
  - rubocop-capybara

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/admin/pay_outs_controller.rb'

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/services.rake'

Metrics/MethodLength:
  Exclude:
    - 'app/mailers/notification_mailer.rb'
    - 'app/controllers/admin/pay_outs_controller.rb'

Metrics/ClassLength:
  Exclude:
    - 'test/controllers/admin/contributions_controller_test.rb'
    - 'test/controllers/admin/pay_outs_controller_test.rb'

Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/users/registrations_controller.rb'
    - 'app/controllers/users/sessions_controller.rb'

Rails/StrongParametersExpect:
  Exclude:
    - 'app/controllers/notification_preferences_controller.rb'
