AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'

require:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-minitest

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/admin/pay_outs_controller.rb'

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/services.rake'

Metrics/MethodLength:
  Exclude:
    - 'app/mailers/notification_mailer.rb'
    - 'app/controllers/admin/pay_outs_controller.rb'

Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/users/registrations_controller.rb'
    - 'app/controllers/users/sessions_controller.rb'
