default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: flourish_development
  cache:
    <<: *default
    database: flourish_development_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: flourish_development_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: flourish_development_cable
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *default
    database: flourish_test

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *default
    url: <%= ENV["CACHE_DATABASE_URL"] %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    url: <%= ENV["QUEUE_DATABASE_URL"] %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    url: <%= ENV["CABLE_DATABASE_URL"] %>
    migrations_paths: db/cable_migrate
