service: flourish
image: flourish

servers:
  web:
    hosts:
      - 52.62.31.62
    options:
      memory: 512m

volumes:
  - "/data/flourish:/rails/storage/db"

proxy:
  ssl: true
  host: flourish.buzz
  app_port: 80
  healthcheck:
    timeout: 120

registry:
  server: 416802459241.dkr.ecr.ap-southeast-2.amazonaws.com

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

asset_path: /rails/public/assets

builder:
  arch: amd64

ssh:
  user: ubuntu
  keys:
    - ~/.ssh/cassar-code.pem
