service: flourish
image: flourish

servers:
  web:
    hosts:
      - 15.135.194.185
    options:
      memory: 512m

volumes:
  - "/data/flourish:/rails/storage/db"

proxy:
  ssl: true
  host: flourish.buzz
  app_port: 80

registry:
  server: 416802459241.dkr.ecr.ap-southeast-2.amazonaws.com
  username: AWS
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

asset_path: /rails/public/assets

ssh:
  user: ubuntu
  keys:
    - ~/.ssh/cassar-code.pem
