servers:
  web:
    hosts:
      - 100.115.240.52

proxy:
  ssl: false
  host: flourish.buzz

env:
  secret:
    - RAILS_MASTER_KEY
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY

builder:
  arch: amd64
  remote: ssh://home-server

ssh:
  user: ubuntu
  keys:
    - ~/.ssh/home-server
